<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Exporters\" />
    <Folder Include="Importers\" />
    <Folder Include="Configuration\" />
    <Folder Include="Repositories\" />
    <Folder Include="Persistence\" />
    <Folder Include="Parsers\" />
    <Folder Include="Readers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DFIR.Application\DFIR.Application.csproj" />
    <ProjectReference Include="..\DFIR.Domain\DFIR.Domain.csproj" />
    <ProjectReference Include="..\DFIR.Shared\DFIR.Shared.csproj" />
  </ItemGroup>

</Project>
