<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DFIR.Domain\DFIR.Domain.csproj" />
    <ProjectReference Include="..\DFIR.Shared\DFIR.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
    <Folder Include="DTOs\Common\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Behaviours\" />
    <Folder Include="Validators\" />
    <Folder Include="Queries\" />
    <Folder Include="Pipelines\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
