<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Graphs\" />
    <Folder Include="Engine\" />
    <Folder Include="Timeline\" />
    <Folder Include="Strategies\" />
  </ItemGroup>

</Project>
